server:
  port: 80
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

#默认使用配置
spring:
  profiles:
    active: prod

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.wang.entity
  mapperLocations: classpath:mapper/*.xml

---

#开发配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.32.21:3306/bootdo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations：classpath:file:///root/bigdata_jar/images